services:
  app_api:
    build:
      context: .
      dockerfile: app/DockerFile
    container_name: app_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://avnadmin:AVNS_uB3eS5nBg9hbv93vLAa@hediyele-hediyele.h.aivencloud.com/defaultdb
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: app_db
    environment:
      POSTGRES_DB: defaultdb
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: AVNS_uB3eS5nBg9hbv93vLAa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
